### ISSUE TITLE
Compatibility with pandas v2

### ISSUE THREAD

**Issue by pllim** [bqplot/bqplot#1586]
Hello, `pandas` v2.0.0rc0 is out and I see this pin:

https://github.com/bqplot/bqplot/blob/de13cf32532de55746817924e0cec45a06b6dc28/setup.cfg#L19

Do you have plans to ensure compatibility with `pandas` v2? Thanks!

**Comment by giswqs** [comment]
Just ran into the same issue. Pandas 2.0 was out a few days ago. Will bqplot be compatible with Pandas 2.0 in the next release? If yes, I will wait for the next release. Otherwise, I need to pin the pandas version in downstream packages. 

![image](https://user-images.githubusercontent.com/5016453/230465247-3c0b3b71-86b3-40fe-922b-c58e3cbe7628.png)

**Comment by maartenbreddels** [comment]
I don't think we should pin like this, and #1587 already tried to get rid of this pin.
I rebased the PR, lets see if it goes green.
